### ISSUE TITLE
LENS

### ISSUE THREAD

**Issue by Skyrimus** [Skyrimus/Pixi3_5_Oreo_Kernel_3.18.79#1]
Not working autofocus

**Comment by ghost** [comment]
Explain the problem

**Comment by Skyrimus** [comment]
I have my stock hals for cameras and focus, but it not works on oreo, i use my own writed driver for autofocus on 3.18.19 and 3.18.35, if i use it on 3.18.79 focus not works

**Comment by ghost** [comment]
Leave a logcat and dmesg here

**Comment by Skyrimus** [comment]
Fixed
